### ISSUE TITLE
guard.logout 内含 redirect 导致请求被取消

### ISSUE THREAD

**Issue by jd0gx** [Authing/Guard#179]
"@authing/guard-react18@5.1.2"

错误信息，可以看到登出实际上是失败了的
<img width="989" alt="image" src="https://user-images.githubusercontent.com/4531670/216580668-013cd320-d397-4d2c-820a-5612fc33db8d.png">

复现代码
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4531670/216580797-b7b84903-0fc3-4e75-9bd7-65ecb58443a8.png">

源码应该在这。我理解是这个 preflight OPTIONS 占用了时间
https://github.com/Authing/Guard/blob/211cf14071c55ac4d47ea9b64972850cbe16c31b/packages/guard-shim-react18/src/index.tsx#L418-L444

**Comment by zhaoyiming0803** [comment]
你好，我这边用 examples 中的代码看了下，5.1.2 暂时没有复现以上问题哈。目前最新版是 5.1.3-alpha.17，下周会发正式版。

你可以先用 5.1.3-alpha.17 尝试复现下，有问题随时沟通，我来跟进。

**Comment by jchnxu** [comment]
你可以看下我贴的代码。。复现是概率性的。但逻辑上来说是不完备的，因为 window.location.href = 和 auth.logout 处于同一个 callback 内

另外还有一个问题是 `localStorage.clear()` 会影响到别的 localStorage 数据

**Comment by zhaoyiming0803** [comment]
> 你可以看下我贴的代码。。复现是概率性的。但逻辑上来说是不完备的，因为 window.location.href = 和 auth.logout 处于同一个 callback 内
> 
> 另外还有一个问题是 `localStorage.clear()` 会影响到别的 localStorage 数据

以上两个问题在 5.1.3-alpha.17 中已修复。
