### ISSUE TITLE
production 无法登录

### ISSUE THREAD

**Issue by addlistener** [Authing/Guard#212]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/4531670/236385167-96c0cb71-89c3-4a2f-8550-0686c703921a.png">

从localhost换到了线上环境(https)，这是报的错。。我也有点懵

然后本地改了hosts试(http)，也不行。现象是不跳转
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4531670/236389805-08e5c023-afb1-4f7c-98bc-c7d473b8d381.png">

我的console配置
<img width="945" alt="image" src="https://user-images.githubusercontent.com/4531670/236389558-bff52c74-ab2a-4835-94af-a482ebff2b9c.png">

**Comment by zhaoyiming0803** [comment]
可否提供一个最小复现 demo，放到 cdn，我看下。

**Comment by addlistener** [comment]
是 swc 的问题，感谢支持 💯
